//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.21 at 03:43:38 PM GMT 
//


package com.metabroadcast.nonametv.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "present",
    "stereo"
})
@XmlRootElement(name = "audio")
public class Audio {

    protected String present;
    protected String stereo;

    /**
     * Gets the value of the present property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresent() {
        return present;
    }

    /**
     * Sets the value of the present property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresent(String value) {
        this.present = value;
    }

    /**
     * Gets the value of the stereo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStereo() {
        return stereo;
    }

    /**
     * Sets the value of the stereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStereo(String value) {
        this.stereo = value;
    }

}
